### ISSUE TITLE
RDMRose Learning Materials

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#73] opened 2018-09-17 16:19 UTC
Information about registered data management training resource

- [ ] Date resource added: 09/17/2018
- [ ] Registered by: jawikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10208

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment] 2019-04-20 22:06
This is a duplicate of http://dmtclearinghouse.esipfed.org/node/10302

**Closed** 2019-04-20 22:08 UTC
