### ISSUE TITLE
MANTRA Research Data Management Training

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#72] opened 2018-09-17 15:37 UTC
Information about registered data management training resource

- [ ] Date resource added: 09/17/2018
- [ ] Registered by: jawikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10207

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment] 2019-04-20 21:57
This is a duplicate of http://dmtclearinghouse.esipfed.org/node/9896, so has been deleted.

**Closed** 2019-04-20 21:58 UTC
